application: bingwp7
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /files
  static_dir: files
- url: /fetch
  script: bing4wp7.app
  login: admin
- url: /.*
  script: bing4wp7.app
